name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Smoke test - import modules
        run: |
          python - << 'PY'
          import cv2
          import numpy
          import PIL
          import importlib
          import sys
          print('Python', sys.version)
          print('OpenCV', cv2.__version__)
          print('Numpy', numpy.__version__)
          print('Pillow', PIL.__version__)
          PY
