name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (minimal for smoke test)
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python numpy Pillow

      - name: Smoke test - import modules
        shell: bash
        run: |
          python - << 'PY'
          import cv2
          import numpy
          import PIL
          import sys
          print('Python', sys.version)
          print('OpenCV', cv2.__version__)
          print('Numpy', numpy.__version__)
          print('Pillow', PIL.__version__)
          PY
